name: Upload Win CLI x64 from Google Drive

on:
  workflow_dispatch:

# permissions:
  # contents: write

jobs:
  upload-cli:
    runs-on: ubuntu-latest
    
    steps:
      # ---------------------------
      # Install latest rclone
      # ---------------------------
      - name: Install latest rclone
        run: |
          curl -Of https://downloads.rclone.org/rclone-current-linux-amd64.zip
          unzip rclone-current-linux-amd64.zip
          cd rclone-*-linux-amd64
          sudo cp rclone /usr/bin/
          sudo chmod 755 /usr/bin/rclone
          rclone version
      
      # - name: Install rclone
      #   run: sudo apt-get update && sudo apt-get install -y rclone zip

      # - name: Write service account file
      #   run: |
      #     # This assumes you have a service account JSON in your repo secrets
      #     # Create a service account JSON file
      #     echo "${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT }}" > service-account.json

      # - name: Configure rclone for Google Drive
      #   run: |
      #     rclone config create gdrive drive scope=drive.readonly service_account_file=service-account.json

      # ---------------------------
      # Setup service account remote
      # ---------------------------
      - name: Configure rclone remote
        env:
          GOOGLE_DRIVE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT }}
        run: |
          echo "$GOOGLE_DRIVE_SERVICE_ACCOUNT" > sa.json

          cat > rclone.conf <<EOF
          [gdrive]
          type = drive
          scope = drive.readonly
          service_account_file = sa.json
          root_folder_id =
          team_drive =
          EOF

          cat rclone.conf

      # - name: Copy folder from Google Drive
      #   run: |
      #     # Copy the folder by ID into a local folder with the desired name
      #     rclone copy gdrive: "Nidam Benchmark - Win x64 cli" --drive-root-folder-id=1Na7eFh0oBMnmihSDG26DvdIDFAKAwEMQ --create-empty-src-dirs
      
      # ---------------------------
      # Copy folder from Drive using folder ID
      # ---------------------------
      - name: Copy folder by ID
        run: |
          rclone --config=rclone.conf copy \
            gdrive: "Nidam Benchmark - Win x64 cli" --drive-root-folder-id=1Na7eFh0oBMnmihSDG26DvdIDFAKAwEMQ --create-empty-src-dirs -vv

      - name: Zip the folder
        run: |
          zip -r "Nidam Benchmark - Win x64 cli.zip" "Nidam Benchmark - Win x64 cli"

      - name: Upload to existing release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "2.0"
          files: "Nidam Benchmark - Win x64 cli.zip"
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
