name: Upload Win CLI x64 from Google Drive

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload-cli:
    runs-on: ubuntu-latest
    
    steps:
      # ---------------------------
      # Install latest rclone
      # ---------------------------
      - name: Install latest rclone
        run: |
          curl -Of https://downloads.rclone.org/rclone-current-linux-amd64.zip
          unzip rclone-current-linux-amd64.zip
          cd rclone-*-linux-amd64
          sudo cp rclone /usr/bin/
          sudo chmod 755 /usr/bin/rclone
          rclone version

      # ---------------------------
      # Setup service account remote
      # ---------------------------
      - name: Configure rclone remote
        env:
          GOOGLE_DRIVE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT }}
        run: |
          echo "$GOOGLE_DRIVE_SERVICE_ACCOUNT" > sa.json

          cat > rclone.conf <<EOF
          [gdrive]
          type = drive
          scope = drive.readonly
          service_account_file = sa.json
          EOF

          cat rclone.conf

      # ---------------------------
      # Copy folder from Drive using folder ID
      # ---------------------------
      - name: Copy folder by ID
        run: |
          rclone --config=rclone.conf copy \
            gdrive: "Nidam Benchmark - Win x64 cli" --drive-root-folder-id=1Na7eFh0oBMnmihSDG26DvdIDFAKAwEMQ --create-empty-src-dirs -vv

      - name: Zip the folder
        run: |
          zip -r "Nidam Benchmark - Win x64 cli.zip" "Nidam Benchmark - Win x64 cli"

      - name: Upload to existing release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "2.0"
          files: "Nidam Benchmark - Win x64 cli.zip"
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
